

server:
  port: 8555
  servlet:
    context-path: /tech-bazzar-picture

spring:
  servlet:
    multipart:
      max-file-size: 5MB

  datasource:
    url: ${url_db}
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}

  flyway:
    baselineOnMigrate: true
    url: ${url_db}
    user: ${db_username}
    password: ${db_password}
    validateOnMigrate: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update

integrations:
  auth-service:
    url: http://localhost:8181/tech-bazzar-user/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  cart-service:
    url: http://localhost:8182/tech-bazzar-cart/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  organization-service:
    url: http://localhost:8185/tech-bazzar-organization/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

  core-service:
    url: http://localhost:8183/tech-bazzar-core/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
springdoc:
  swagger-ui:
    supported-submit-methods: "get"

  #  springdoc.swagger-ui.supportedSubmitMethods = Array=[, "put", "post","patch"]