server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
            allowedHeaders: "*"


      routes:
        - id: front-service
          uri: http://localhost:3000
          predicates:
            - Path=/front/**
          filters:
            - StripPrefix=1
            - PrefixPath=/front
            - JwtAuthFilter

        - id: core-service
          uri: http://localhost:8183
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/simple-store-core
            - JwtAuthFilter
        #            - NotForGuestsFilter

        - id: cart-service
          uri: http://localhost:8182
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/simple-store-cart
            - JwtAuthFilter
            - NotForGuestsFilter

        - id: auth-service
          uri: http://localhost:8181
          predicates:
            - Path=/auth/api/v1/users/set_role
          filters:
            - StripPrefix=1
            - PrefixPath=/simple-store-auth
            - JwtAuthFilter
            - NotForRoleUserFilter
        - id: auth-service
          uri: http://localhost:8181
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/simple-store-auth
            - JwtAuthFilter

jwt:
  secret: ${jwt_secret}